import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/context/toast.context";
import Navbar from "@/components/navbar";
import { DataProvider } from "@/context/data.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <DataProvider>
        <ToastProvider>
          <Navbar />
          {children}
        </ToastProvider>
      </DataProvider>
      </body>
    </html>
  );
}
